#!/bin/sh
if [ "$1" != "" ]
then
    curl -L -k https://localhost/sys/fetch_changesets?id=`echo $1 | sed 's/\/.*\/\([^\.]*\)\(\..*\)\?/\1/'`
else
    curl -L -k https://localhost/sys/fetch_changesets?id=`echo $PWD | sed 's/\/.*\/\([^\.]*\)\(\..*\)\?/\1/'`
fi

