#!/bin/sh
if [ "$1" != "" ]
then
    wget -q -O /dev/null http://localhost/sys/fetch_changesets?id=`echo $1 | sed 's/\/.*\/\([^\.]*\)\(\..*\)\?/\1/'`
else
    wget -q -O /dev/null http://localhost/sys/fetch_changesets?id=`echo $PWD | sed 's/\/.*\/\([^\.]*\)\(\..*\)\?/\1/'`
fi

